import type { Metadata } from "next";
import {
  DM_Sans,
  IBM_Plex_Sans,
  Playfair_Display,
  Sora,
} from "next/font/google";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import "../styles/layout/navbar.scss";
import "../styles/layout/footer.scss";
import "../styles/components/button.scss";
import "../styles/pages/homepage.scss";

import "./globals.scss";

import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

import Provider from "./providers";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  display: "swap",
  style: ["normal", "italic"],
});

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  display: "swap",
  style: ["normal", "italic"],
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
  style: ["normal", "italic"],
});

const sora = Sora({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  display: "swap",
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Ventarca",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.className} ${ibmPlexSans.className} ${playfairDisplay.className} ${sora.className}`}
    >
      <body>
        <Provider>
          <Navbar />

          {children}

          <Footer />
        </Provider>
      </body>
    </html>
  );
}
