export const industriesFake: string[] = [
  "AI",
  "Applications",
  "Automotive",
  "Business",
  "Content",
  "Crypto",
  "Design and Style",
  "Ecommerce",
  "Education",
  "Electronics",
  "Entertainment",
  "Entertainment",
  "General Knowledge",
  "Health and Beauty",
  "Hobbies and Games",
  "Home and Garden",
  "Internet",
  "Lifestyle",
  "SaaS",
  "Services",
  "Sports and Outdoor",
  "Technology",
  "Travel",
];
